version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./config/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./config/etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: php:8.0.10-fpm
        container_name: php
        restart: always
        volumes:
            - "./config/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
            - "./config:/config"
            - "./logs:/logs"
        command: sh -c 'docker-php-ext-install pdo_mysql && php-fpm'
    composer:
        image: composer:latest
        container_name: composer
        user: "1000:1000"
        volumes:
            - "./web/backend:/app"
        command: install
    dev:
        build:
            context: .
            dockerfile: ./dev/Dockerfile
        container_name: dev
        volumes:
            - ".:/app"
    mysqldb:
        image: mysql:8
        platform: linux/x86_64
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=website
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        user: "${UID}:${GID}"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        volumes:
            - "./config/etc/phpmyadmin/apache2.conf:/etc/apache2/apache2.conf"
        ports:
            - "127.0.0.1:8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysqldb
